camera:
  rtsp_url: "rtsp://admin:L2688A29@192.168.199.44:554/cam/realmonitor?channel=1&subtype=1"  # Updated camera source
  frame_rate: 20   # Số khung hình xử lý mỗi giây
  resolution: [480, 360]  # Increased resolution to improve frame size

yolo:
  model_path: "yolov8l.pt"
  confidence_threshold: 0.5
  iou_threshold: 0.4

tracker:
  type: "DeepSORT"
  max_age: 30  # Số khung hình theo dõi trước khi mất mục tiêu
  min_hits: 3

lstm:
  sequence_length: 10
  epochs: 50
  batch_size: 16
  learning_rate: 0.001

dataset:
  image_folder: "data/images/"
  label_folder: "data/labels/"
  trained_model_path: "data/trained_model.h5"

mysql:
  host: "localhost"
  user: "root"
  password: "@LamNgocTu1804"
  database: "people_control"